// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using CashSwift.Finacle.Integration.DataAccess.Entities;

namespace CashSwift.Finacle.Integration.DataAccess
{
    public partial class DepositorServerContext
    {

        [DbFunction("funGetUserGroupHierarchyByID", "dbo")]
        public IQueryable<funGetUserGroupHierarchyByIDResult> funGetUserGroupHierarchyByID(int? parent)
        {
            return FromExpression(() => funGetUserGroupHierarchyByID(parent));
        }

        [DbFunction("TranslateSystemTextItem", "dbo")]
        public static string TranslateSystemTextItem(string Language, Guid? SystemTextItem)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("TranslateUserTextItem", "dbo")]
        public static string TranslateUserTextItem(string Language, Guid? UserTextItem)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<funGetUserGroupHierarchyByIDResult>().HasNoKey();
        }
    }
}
