// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CashSwift.Finacle.Integration.DataAccess.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace CashSwift.Finacle.Integration.DataAccess
{
    public partial interface IDepositorServerContextProcedures
    {
        Task<PingResponse> GetLatestPingRequestAsync(string key, CancellationToken cancellationToken = default);
        Task<CheckAccountAgainstAccountPermissionResult> CheckAccountAgainstAccountPermissionAsync(int? TxTypeID, string AccountNumber, string Language, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetAccountListByTxTypeIdResult>> GetAccountListByTxTypeIdAsync(int? TxTypeID, int? ListType, int? Skip, int? Take, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetCITDenominationByDatesResult>> GetCITDenominationByDatesAsync(DateTime? startDate, DateTime? endDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetDestinationEmailsByAlertTypeResult>> GetDestinationEmailsByAlertTypeAsync(int? alertMessageTypeID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetDeviceConfigByUserGroupResult>> GetDeviceConfigByUserGroupAsync(int? ConfigGroup, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetDeviceUsersByDeviceResult>> GetDeviceUsersByDeviceAsync(int? Device_UserGroup, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetFailedPostTransactionsByDateResult>> GetFailedPostTransactionsByDateAsync(DateTime? StartDate, DateTime? EndDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<HashTransactionResult>> HashTransactionAsync(string TxString, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<procInsCITPostingResult>> procInsCITPostingAsync(int? post_status, Guid? cit_tx_id, string dr_account, string dr_currency, long? dr_amount, string cr_account, string cr_currency, long? cr_amount, string narration, DateTime? init_date, Guid? initialising_user, bool? device_initiated, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<procInsTransactionPostingResult>> procInsTransactionPostingAsync(int? post_status, Guid? tx_id, string dr_account, string dr_currency, long? dr_amount, string cr_account, string cr_currency, long? cr_amount, string narration, DateTime? init_date, Guid? initialising_user, bool? device_initiated, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<procUpdCITPostingAuthResult>> procUpdCITPostingAuthAsync(Guid? id, int? post_status, Guid? cit_tx_id, DateTime? auth_date, Guid? authorising_user, int? auth_response, string reason, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<procUpdTransactionPostingAuthResult>> procUpdTransactionPostingAuthAsync(Guid? id, int? post_status, Guid? tx_id, DateTime? auth_date, Guid? authorising_user, int? auth_response, string reason, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SearchAccountResult>> SearchAccountAsync(string SearchText, int? TxTypeID, int? ListType, int? Skip, int? Take, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
