// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("AccountPermissionItem", Schema = "cb")]
    [Index("account", Name = "iaccount_cb_AccountPermissionItem_9A304E1D")]
    [Index("account_permission", Name = "iaccount_permission_cb_AccountPermissionItem_AA7B1243")]
    public partial class AccountPermissionItem
    {
        [Key]
        public Guid id { get; set; }
        public Guid account_permission { get; set; }
        public Guid account { get; set; }
        public Guid? error_message { get; set; }

        [ForeignKey("account")]
        [InverseProperty("AccountPermissionItems")]
        public virtual Account accountNavigation { get; set; }
        [ForeignKey("account_permission")]
        [InverseProperty("AccountPermissionItems")]
        public virtual AccountPermission account_permissionNavigation { get; set; }
    }
}