// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("AccountLedgerItem", Schema = "cb")]
    public partial class AccountLedgerItem
    {
        [Key]
        public Guid id { get; set; }
        [StringLength(50)]
        public string cb_tx_number { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime post_date { get; set; }
        [StringLength(50)]
        public string dr_account_number { get; set; }
        [StringLength(3)]
        public string dr_currency { get; set; }
        public long? dr_amount { get; set; }
        [StringLength(50)]
        public string cr_account_number { get; set; }
        [StringLength(3)]
        public string cr_currency { get; set; }
        public long? cr_amount { get; set; }
        [StringLength(100)]
        public string narration { get; set; }
        public Guid? dr_account { get; set; }
        public Guid? cr_account { get; set; }
    }
}