// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("AccountPermission", Schema = "cb")]
    [Index("tx_type", Name = "UX_AccountPermission_tx_type", IsUnique = true)]
    public partial class AccountPermission
    {
        public AccountPermission()
        {
            AccountPermissionItems = new HashSet<AccountPermissionItem>();
            TransactionTypeListItems = new HashSet<TransactionTypeListItem>();
        }

        [Key]
        public Guid id { get; set; }
        public int tx_type { get; set; }
        public int list_type { get; set; }
        public Guid? error_message { get; set; }
        public bool enabled { get; set; }

        [ForeignKey("tx_type")]
        [InverseProperty("AccountPermission")]
        public virtual TransactionTypeListItem tx_typeNavigation { get; set; }
        [InverseProperty("account_permissionNavigation")]
        public virtual ICollection<AccountPermissionItem> AccountPermissionItems { get; set; }
        [InverseProperty("account_permissionNavigation")]
        public virtual ICollection<TransactionTypeListItem> TransactionTypeListItems { get; set; }
    }
}