// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("Account", Schema = "cb")]
    [Index("account_number", Name = "UX_account_number", IsUnique = true)]
    public partial class Account
    {
        public Account()
        {
            AccountPermissionItems = new HashSet<AccountPermissionItem>();
        }

        [Key]
        public Guid id { get; set; }
        public byte[] Icon { get; set; }
        [StringLength(3)]
        public string currency { get; set; }
        [StringLength(50)]
        public string account_number { get; set; }
        [StringLength(100)]
        public string account_name { get; set; }
        public bool? enabled { get; set; }
        [StringLength(150)]
        public string FullName { get; set; }

        [InverseProperty("accountNavigation")]
        public virtual ICollection<AccountPermissionItem> AccountPermissionItems { get; set; }
    }
}