// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    /// <summary>
    /// a task a user needs permission to perform
    /// </summary>
    [Table("Activity")]
    public partial class Activity
    {
        public Activity()
        {
            Permissions = new HashSet<Permission>();
        }

        [Key]
        public Guid id { get; set; }
        /// <summary>
        /// The name of the activity. will be used in lookups
        /// </summary>
        [Required]
        [StringLength(50)]
        public string name { get; set; }
        /// <summary>
        /// Short description of the activity being performed
        /// </summary>
        [StringLength(255)]
        public string description { get; set; }

        [InverseProperty("activity")]
        public virtual ICollection<Permission> Permissions { get; set; }
    }
}