// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    /// <summary>
    /// Register a role to receive an alert
    /// </summary>
    [Table("AlertMessageRegistry")]
    [Index("alert_type_id", "role_id", Name = "UX_AlertMessageRegistry", IsUnique = true)]
    [Index("alert_type_id", Name = "ialert_type_id_AlertMessageRegistry")]
    [Index("role_id", Name = "irole_id_AlertMessageRegistry")]
    public partial class AlertMessageRegistry
    {
        [Key]
        public Guid id { get; set; }
        /// <summary>
        /// The type of alert the role can receive
        /// </summary>
        public int alert_type_id { get; set; }
        /// <summary>
        /// The role that will be given rights to the AlertMssage type
        /// </summary>
        public Guid role_id { get; set; }
        /// <summary>
        /// Can the role receive email
        /// </summary>
        [Required]
        public bool? email_enabled { get; set; }
        /// <summary>
        /// Can the role receive an SMS message for the alert message type
        /// </summary>
        public bool phone_enabled { get; set; }

        [ForeignKey("alert_type_id")]
        [InverseProperty("AlertMessageRegistries")]
        public virtual AlertMessageType alert_type { get; set; }
        [ForeignKey("role_id")]
        [InverseProperty("AlertMessageRegistries")]
        public virtual Role role { get; set; }
    }
}