// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("APIUser", Schema = "api")]
    [Index("AppId", Name = "UX_API_ID", IsUnique = true)]
    public partial class APIUser
    {
        [Key]
        public Guid id { get; set; }
        [StringLength(128)]
        public string Name { get; set; }
        public bool? Enabled { get; set; }
        public Guid AppId { get; set; }
        [Required]
        [MaxLength(32)]
        public byte[] AppKey { get; set; }
    }
}