// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("ApplicationUserLoginDetail")]
    [Index("GCRecord", Name = "iGCRecord_ApplicationUserLoginDetail")]
    [Index("LastLoginLogEntry", Name = "iLastLoginLogEntry_ApplicationUserLoginDetail")]
    [Index("User", Name = "iUser_ApplicationUserLoginDetail")]
    public partial class ApplicationUserLoginDetail
    {
        public ApplicationUserLoginDetail()
        {
            ApplicationUsers = new HashSet<ApplicationUser>();
            UserLocks = new HashSet<UserLock>();
            WebPortalLogins = new HashSet<WebPortalLogin>();
        }

        [Key]
        public Guid Oid { get; set; }
        public Guid? User { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastPasswordDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastLoginDate { get; set; }
        public Guid? LastLoginLogEntry { get; set; }
        public int? FailedLoginCount { get; set; }
        [StringLength(100)]
        public string OTP { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? OTPExpire { get; set; }
        [StringLength(100)]
        public string OTPEnabled { get; set; }
        [StringLength(128)]
        public string ResetEmailCode { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ResetEmailExpire { get; set; }
        public bool? ResetEmailEnabled { get; set; }
        public int? OptimisticLockField { get; set; }
        public int? GCRecord { get; set; }

        [ForeignKey("LastLoginLogEntry")]
        [InverseProperty("ApplicationUserLoginDetails")]
        public virtual WebPortalLogin LastLoginLogEntryNavigation { get; set; }
        [ForeignKey("User")]
        [InverseProperty("ApplicationUserLoginDetails")]
        public virtual ApplicationUser UserNavigation { get; set; }
        [InverseProperty("ApplicationUserLoginDetailNavigation")]
        public virtual ICollection<ApplicationUser> ApplicationUsers { get; set; }
        [InverseProperty("ApplicationUserLoginDetailNavigation")]
        public virtual ICollection<UserLock> UserLocks { get; set; }
        [InverseProperty("ApplicationUserLoginDetailNavigation")]
        public virtual ICollection<WebPortalLogin> WebPortalLogins { get; set; }
    }
}