// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("ApplicationException", Schema = "exp")]
    [Index("device_id", Name = "idevice_id_exp_ApplicationException_8807CB70")]
    public partial class ApplicationException
    {
        [Key]
        public Guid id { get; set; }
        public Guid device_id { get; set; }
        public DateTime datetime { get; set; }
        public int code { get; set; }
        [StringLength(50)]
        public string name { get; set; }
        public int level { get; set; }
        [StringLength(255)]
        public string message { get; set; }
        [StringLength(255)]
        public string additional_info { get; set; }
        public string stack { get; set; }
        [Required]
        [StringLength(50)]
        public string machine_name { get; set; }
    }
}