// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("ApplicationUserChangePassword")]
    [Index("GCRecord", Name = "iGCRecord_ApplicationUserChangePassword")]
    [Index("PasswordPolicy", Name = "iPasswordPolicy_ApplicationUserChangePassword")]
    [Index("User", Name = "iUser_ApplicationUserChangePassword")]
    public partial class ApplicationUserChangePassword
    {
        [Key]
        public Guid Oid { get; set; }
        public int? OptimisticLockField { get; set; }
        public int? GCRecord { get; set; }
        [StringLength(100)]
        public string OldPassword { get; set; }
        [StringLength(100)]
        public string NewPassword { get; set; }
        [StringLength(100)]
        public string ConfirmPassword { get; set; }
        public Guid? User { get; set; }
        public Guid? PasswordPolicy { get; set; }

        [ForeignKey("PasswordPolicy")]
        [InverseProperty("ApplicationUserChangePasswords")]
        public virtual PasswordPolicy PasswordPolicyNavigation { get; set; }
        [ForeignKey("User")]
        [InverseProperty("ApplicationUserChangePasswords")]
        public virtual ApplicationUser UserNavigation { get; set; }
    }
}