// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("AuditDataItemPersistent")]
    [Index("AuditedObject", Name = "iAuditedObject_AuditDataItemPersistent")]
    [Index("GCRecord", Name = "iGCRecord_AuditDataItemPersistent")]
    [Index("ModifiedOn", Name = "iModifiedOn_AuditDataItemPersistent")]
    [Index("NewObject", Name = "iNewObject_AuditDataItemPersistent")]
    [Index("OldObject", Name = "iOldObject_AuditDataItemPersistent")]
    [Index("OperationType", Name = "iOperationType_AuditDataItemPersistent")]
    [Index("UserName", Name = "iUserName_AuditDataItemPersistent")]
    public partial class AuditDataItemPersistent
    {
        [Key]
        public Guid Oid { get; set; }
        [StringLength(100)]
        public string UserName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedOn { get; set; }
        [StringLength(100)]
        public string OperationType { get; set; }
        [StringLength(2048)]
        public string Description { get; set; }
        public Guid? AuditedObject { get; set; }
        public Guid? OldObject { get; set; }
        public Guid? NewObject { get; set; }
        [StringLength(1024)]
        public string OldValue { get; set; }
        [StringLength(1024)]
        public string NewValue { get; set; }
        [StringLength(100)]
        public string PropertyName { get; set; }
        public int? OptimisticLockField { get; set; }
        public int? GCRecord { get; set; }

        [ForeignKey("AuditedObject")]
        [InverseProperty("AuditDataItemPersistents")]
        public virtual AuditedObjectWeakReference AuditedObjectNavigation { get; set; }
        [ForeignKey("NewObject")]
        [InverseProperty("AuditDataItemPersistentNewObjectNavigations")]
        public virtual XPWeakReference NewObjectNavigation { get; set; }
        [ForeignKey("OldObject")]
        [InverseProperty("AuditDataItemPersistentOldObjectNavigations")]
        public virtual XPWeakReference OldObjectNavigation { get; set; }
    }
}