// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("AuditedObjectWeakReference")]
    public partial class AuditedObjectWeakReference
    {
        public AuditedObjectWeakReference()
        {
            AuditDataItemPersistents = new HashSet<AuditDataItemPersistent>();
        }

        [Key]
        public Guid Oid { get; set; }
        public Guid? GuidId { get; set; }
        public int? IntId { get; set; }
        [StringLength(250)]
        public string DisplayName { get; set; }

        [ForeignKey("Oid")]
        [InverseProperty("AuditedObjectWeakReference")]
        public virtual XPWeakReference OidNavigation { get; set; }
        [InverseProperty("AuditedObjectNavigation")]
        public virtual ICollection<AuditDataItemPersistent> AuditDataItemPersistents { get; set; }
    }
}