// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    /// <summary>
    /// The bank that owns the depositor
    /// </summary>
    [Table("Bank")]
    [Index("country_code", Name = "icountry_code_Bank")]
    public partial class Bank
    {
        public Bank()
        {
            Branches = new HashSet<Branch>();
        }

        [Key]
        public Guid id { get; set; }
        [Required]
        [StringLength(50)]
        public string bank_code { get; set; }
        [Required]
        [StringLength(50)]
        public string name { get; set; }
        [StringLength(255)]
        public string description { get; set; }
        [Required]
        [StringLength(2)]
        [Unicode(false)]
        public string country_code { get; set; }

        [ForeignKey("country_code")]
        [InverseProperty("Banks")]
        public virtual Country country_codeNavigation { get; set; }
        [InverseProperty("bank")]
        public virtual ICollection<Branch> Branches { get; set; }
    }
}