// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    /// <summary>
    /// status of the communication service for email, sms etc
    /// </summary>
    [Table("CashSwiftCommunicationServiceStatus")]
    public partial class CashSwiftCommunicationServiceStatus
    {
        [Key]
        public int id { get; set; }
        public int email_status { get; set; }
        public int email_error { get; set; }
        public string email_error_message { get; set; }
        public int sms_status { get; set; }
        public int sms_error { get; set; }
        public string sms_error_message { get; set; }
        public DateTime modified { get; set; }
    }
}