// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    public partial class CheckAccountAgainstAccountPermissionResult
    {
        public Guid id { get; set; }
        public byte[] Icon { get; set; }
        public string currency { get; set; }
        public string account_name { get; set; }
        public bool? enabled { get; set; }
        public string error_message { get; set; }
    }
}
