// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    /// <summary>
    /// currency and deomination breakdown of the CIT bag
    /// </summary>
    [Index("cit_id", Name = "icit_id_CITDenominations")]
    [Index("currency_id", Name = "icurrency_id_CITDenominations")]
    public partial class CITDenomination
    {
        [Key]
        public Guid id { get; set; }
        /// <summary>
        /// The CIT the record belongs to
        /// </summary>
        public Guid cit_id { get; set; }
        /// <summary>
        /// When this item was recorded
        /// </summary>
        public DateTime? datetime { get; set; }
        /// <summary>
        /// The currency code
        /// </summary>
        [Required]
        [StringLength(3)]
        [Unicode(false)]
        public string currency_id { get; set; }
        /// <summary>
        /// denomination of note or coin in major currency
        /// </summary>
        public int denom { get; set; }
        /// <summary>
        /// How many of the denomination were counted
        /// </summary>
        public long count { get; set; }
        /// <summary>
        /// The subtotal of the denomination calculated as denom*count
        /// </summary>
        public long subtotal { get; set; }

        [ForeignKey("cit_id")]
        [InverseProperty("CITDenominations")]
        public virtual CIT cit { get; set; }
        [ForeignKey("currency_id")]
        [InverseProperty("CITDenominations")]
        public virtual Currency currency { get; set; }
    }
}