// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("CITPosting")]
    [Index("authorising_user", Name = "iauthorising_user_CITPosting")]
    [Index("cit_tx_id", Name = "icit_tx_id_CITPosting")]
    [Index("initialising_user", Name = "iinitialising_user_CITPosting")]
    public partial class CITPosting
    {
        [Key]
        public Guid id { get; set; }
        [StringLength(50)]
        public string cb_tx_number { get; set; }
        public Guid cit_tx_id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? post_date { get; set; }
        [Required]
        [StringLength(50)]
        public string dr_account { get; set; }
        [Required]
        [StringLength(10)]
        [Unicode(false)]
        public string dr_currency { get; set; }
        public long dr_amount { get; set; }
        [Required]
        [StringLength(50)]
        public string cr_account { get; set; }
        [Required]
        [StringLength(10)]
        [Unicode(false)]
        public string cr_currency { get; set; }
        public long cr_amount { get; set; }
        [StringLength(100)]
        public string narration { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string error_code { get; set; }
        [StringLength(255)]
        public string error_message { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? cb_date { get; set; }
        [StringLength(16)]
        public string cb_tx_status { get; set; }
        [StringLength(100)]
        public string cb_status_detail { get; set; }
        public bool device_initiated { get; set; }
        public int post_status { get; set; }
        public Guid initialising_user { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime init_date { get; set; }
        public Guid? authorising_user { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? auth_date { get; set; }
        public int? auth_response { get; set; }
        [StringLength(100)]
        public string reason { get; set; }
        public bool is_complete { get; set; }

        [ForeignKey("authorising_user")]
        [InverseProperty("CITPostingauthorising_userNavigations")]
        public virtual ApplicationUser authorising_userNavigation { get; set; }
        [ForeignKey("cit_tx_id")]
        [InverseProperty("CITPostings")]
        public virtual CITTransaction cit_tx { get; set; }
        [ForeignKey("initialising_user")]
        [InverseProperty("CITPostinginitialising_userNavigations")]
        public virtual ApplicationUser initialising_userNavigation { get; set; }
    }
}