// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    /// <summary>
    /// Stores CIT receipts
    /// </summary>
    [Table("CITPrintout")]
    [Index("cit_id", Name = "icit_id_CITPrintout")]
    public partial class CITPrintout
    {
        [Key]
        public Guid id { get; set; }
        public DateTime datetime { get; set; }
        /// <summary>
        /// The CIT this rceipt belongs to
        /// </summary>
        public Guid cit_id { get; set; }
        /// <summary>
        /// Receipt SHA512 hash
        /// </summary>
        public Guid print_guid { get; set; }
        /// <summary>
        /// Text of the receipt
        /// </summary>
        public string print_content { get; set; }
        /// <summary>
        /// Is this CIT Receipt a copy, used for marking duplicate receipts
        /// </summary>
        public bool is_copy { get; set; }

        [ForeignKey("cit_id")]
        [InverseProperty("CITPrintouts")]
        public virtual CIT cit { get; set; }
    }
}