// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("CITTransaction")]
    [Index("cit_id", Name = "icit_id_CITTransaction")]
    public partial class CITTransaction
    {
        public CITTransaction()
        {
            CITPostings = new HashSet<CITPosting>();
        }

        [Key]
        public Guid id { get; set; }
        public DateTime datetime { get; set; }
        public Guid cit_id { get; set; }
        [Required]
        [StringLength(3)]
        [Unicode(false)]
        public string currency { get; set; }
        public long amount { get; set; }
        [Required]
        [StringLength(50)]
        public string suspense_account { get; set; }
        [Required]
        [StringLength(50)]
        public string account_number { get; set; }
        [StringLength(50)]
        public string narration { get; set; }
        [StringLength(50)]
        public string cb_tx_number { get; set; }
        public DateTime? cb_date { get; set; }
        [StringLength(50)]
        public string cb_tx_status { get; set; }
        public string cb_status_detail { get; set; }
        public int error_code { get; set; }
        [StringLength(255)]
        public string error_message { get; set; }

        [ForeignKey("cit_id")]
        [InverseProperty("CITTransactions")]
        public virtual CIT cit { get; set; }
        [InverseProperty("cit_tx")]
        public virtual ICollection<CITPosting> CITPostings { get; set; }
    }
}