// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    /// <summary>
    /// Categorisation of configuration opions
    /// </summary>
    [Table("ConfigCategory")]
    public partial class ConfigCategory
    {
        public ConfigCategory()
        {
            Configs = new HashSet<Config>();
        }

        [Key]
        public Guid id { get; set; }
        /// <summary>
        /// Name of the AlertMessage
        /// </summary>
        [Required]
        [StringLength(50)]
        public string name { get; set; }
        [StringLength(255)]
        public string description { get; set; }

        [InverseProperty("category")]
        public virtual ICollection<Config> Configs { get; set; }
    }
}