// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    /// <summary>
    /// Enumeration of allowed Currencies. A device can then associate with a currency list
    /// </summary>
    [Table("CurrencyList")]
    [Index("default_currency", Name = "idefault_currency_CurrencyList")]
    public partial class CurrencyList
    {
        public CurrencyList()
        {
            CurrencyList_Currencies = new HashSet<CurrencyList_Currency>();
            Devices = new HashSet<Device>();
        }

        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(50)]
        public string name { get; set; }
        [Required]
        [StringLength(255)]
        public string description { get; set; }
        [Required]
        [StringLength(3)]
        [Unicode(false)]
        public string default_currency { get; set; }

        [ForeignKey("default_currency")]
        [InverseProperty("CurrencyLists")]
        public virtual Currency default_currencyNavigation { get; set; }
        [InverseProperty("currency_listNavigation")]
        public virtual ICollection<CurrencyList_Currency> CurrencyList_Currencies { get; set; }
        [InverseProperty("currency_listNavigation")]
        public virtual ICollection<Device> Devices { get; set; }
    }
}