// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Index("GCRecord", Name = "iGCRecord_DashboardData")]
    public partial class DashboardDatum
    {
        [Key]
        public Guid Oid { get; set; }
        public string Content { get; set; }
        [StringLength(100)]
        public string Title { get; set; }
        public bool? SynchronizeTitle { get; set; }
        public int? OptimisticLockField { get; set; }
        public int? GCRecord { get; set; }
    }
}