// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Keyless]
    public partial class DenominationView
    {
        public Guid tx_id { get; set; }
        public long? subtotal { get; set; }
        [Column("50")]
        public long _50 { get; set; }
        [Column("100")]
        public long _100 { get; set; }
        [Column("200")]
        public long _200 { get; set; }
        [Column("500")]
        public long _500 { get; set; }
        [Column("1000")]
        public long _1000 { get; set; }
    }
}