// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    /// <summary>
    /// Denomination enumeration for a Transaction
    /// </summary>
    [Table("DenominationDetail")]
    [Index("tx_id", Name = "itx_id_DenominationDetail")]
    public partial class DenominationDetail
    {
        [Key]
        public Guid id { get; set; }
        public Guid tx_id { get; set; }
        /// <summary>
        /// denomination of note or coin in major currency
        /// </summary>
        public int denom { get; set; }
        /// <summary>
        /// How many of the denomination were counted
        /// </summary>
        public long count { get; set; }
        /// <summary>
        /// The subtotal of the denomination calculated as denom*count
        /// </summary>
        public long subtotal { get; set; }
        public DateTime? datetime { get; set; }

        [ForeignKey("tx_id")]
        [InverseProperty("DenominationDetails")]
        public virtual Transaction tx { get; set; }
    }
}