// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("Device")]
    [Index("GUIScreen_list", Name = "iGUIScreen_list_DeviceList")]
    [Index("branch_id", Name = "ibranch_id_DeviceList")]
    [Index("config_group", Name = "iconfig_group_DeviceList")]
    [Index("currency_list", Name = "icurrency_list_DeviceList")]
    [Index("language_list", Name = "ilanguage_list_Device")]
    [Index("transaction_type_list", Name = "itransaction_type_list_DeviceList")]
    [Index("type_id", Name = "itype_id_DeviceList")]
    [Index("user_group", Name = "iuser_group_DeviceList")]
    public partial class Device
    {
        public Device()
        {
            CITs = new HashSet<CIT>();
            DepositorSessions = new HashSet<DepositorSession>();
            DeviceCITSuspenseAccounts = new HashSet<DeviceCITSuspenseAccount>();
            DeviceLocks = new HashSet<DeviceLock>();
            DeviceLogins = new HashSet<DeviceLogin>();
            DevicePrinters = new HashSet<DevicePrinter>();
            DeviceSuspenseAccounts = new HashSet<DeviceSuspenseAccount>();
            Transactions = new HashSet<Transaction>();
        }

        [Key]
        public Guid id { get; set; }
        [Required]
        [StringLength(50)]
        public string device_number { get; set; }
        [Required]
        [StringLength(50)]
        public string device_location { get; set; }
        [Required]
        [StringLength(50)]
        public string name { get; set; }
        [StringLength(128)]
        public string machine_name { get; set; }
        public Guid branch_id { get; set; }
        [StringLength(255)]
        public string description { get; set; }
        public int type_id { get; set; }
        public bool enabled { get; set; }
        public int config_group { get; set; }
        public int? user_group { get; set; }
        public int GUIScreen_list { get; set; }
        public int? language_list { get; set; }
        public int currency_list { get; set; }
        public int transaction_type_list { get; set; }
        /// <summary>
        /// how many cycles of failed logins have been detected. used to lock the machine in case of password guessing
        /// </summary>
        public int login_cycles { get; set; }
        /// <summary>
        /// how many times in a row a login attempt has failed
        /// </summary>
        public int login_attempts { get; set; }
        [StringLength(17)]
        [Unicode(false)]
        public string mac_address { get; set; }
        public Guid app_id { get; set; }
        [Required]
        [MaxLength(32)]
        public byte[] app_key { get; set; }

        [ForeignKey("GUIScreen_list")]
        [InverseProperty("Devices")]
        public virtual GUIScreenList GUIScreen_listNavigation { get; set; }
        [ForeignKey("branch_id")]
        [InverseProperty("Devices")]
        public virtual Branch branch { get; set; }
        [ForeignKey("config_group")]
        [InverseProperty("Devices")]
        public virtual ConfigGroup config_groupNavigation { get; set; }
        [ForeignKey("currency_list")]
        [InverseProperty("Devices")]
        public virtual CurrencyList currency_listNavigation { get; set; }
        [ForeignKey("language_list")]
        [InverseProperty("Devices")]
        public virtual LanguageList language_listNavigation { get; set; }
        [ForeignKey("transaction_type_list")]
        [InverseProperty("Devices")]
        public virtual TransactionTypeList transaction_type_listNavigation { get; set; }
        [ForeignKey("type_id")]
        [InverseProperty("Devices")]
        public virtual DeviceType type { get; set; }
        [ForeignKey("user_group")]
        [InverseProperty("Devices")]
        public virtual UserGroup user_groupNavigation { get; set; }
        [InverseProperty("device")]
        public virtual ICollection<CIT> CITs { get; set; }
        [InverseProperty("device")]
        public virtual ICollection<DepositorSession> DepositorSessions { get; set; }
        [InverseProperty("device")]
        public virtual ICollection<DeviceCITSuspenseAccount> DeviceCITSuspenseAccounts { get; set; }
        [InverseProperty("device")]
        public virtual ICollection<DeviceLock> DeviceLocks { get; set; }
        [InverseProperty("device")]
        public virtual ICollection<DeviceLogin> DeviceLogins { get; set; }
        [InverseProperty("device")]
        public virtual ICollection<DevicePrinter> DevicePrinters { get; set; }
        [InverseProperty("device")]
        public virtual ICollection<DeviceSuspenseAccount> DeviceSuspenseAccounts { get; set; }
        [InverseProperty("device")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}