// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("DeviceCITSuspenseAccount")]
    [Index("currency_code", Name = "icurrency_code_DeviceCITSuspenseAccount")]
    [Index("device_id", Name = "idevice_id_DeviceCITSuspenseAccount")]
    public partial class DeviceCITSuspenseAccount
    {
        [Key]
        public Guid id { get; set; }
        public Guid device_id { get; set; }
        [Required]
        [StringLength(3)]
        [Unicode(false)]
        public string currency_code { get; set; }
        [Required]
        [StringLength(50)]
        public string account_number { get; set; }
        [StringLength(100)]
        public string account_name { get; set; }
        public bool enabled { get; set; }
        public Guid? account { get; set; }

        [ForeignKey("currency_code")]
        [InverseProperty("DeviceCITSuspenseAccounts")]
        public virtual Currency currency_codeNavigation { get; set; }
        [ForeignKey("device_id")]
        [InverseProperty("DeviceCITSuspenseAccounts")]
        public virtual Device device { get; set; }
    }
}