// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("EscrowJam", Schema = "exp")]
    [Index("authorising_user", Name = "iauthorising_user_exp_EscrowJam_EB67F9DC")]
    [Index("initialising_user", Name = "iinitialising_user_exp_EscrowJam_39209E1C")]
    [Index("transaction_id", Name = "itransaction_id_exp_EscrowJam_A9BA55BC")]
    public partial class EscrowJam
    {
        [Key]
        public Guid id { get; set; }
        public Guid transaction_id { get; set; }
        public DateTime date_detected { get; set; }
        public long dropped_amount { get; set; }
        public long escrow_amount { get; set; }
        public long posted_amount { get; set; }
        public long retreived_amount { get; set; }
        public DateTime? recovery_date { get; set; }
        public Guid? initialising_user { get; set; }
        public Guid? authorising_user { get; set; }
        [StringLength(100)]
        public string additional_info { get; set; }

        [ForeignKey("authorising_user")]
        [InverseProperty("EscrowJamauthorising_userNavigations")]
        public virtual ApplicationUser authorising_userNavigation { get; set; }
        [ForeignKey("initialising_user")]
        [InverseProperty("EscrowJaminitialising_userNavigations")]
        public virtual ApplicationUser initialising_userNavigation { get; set; }
        [ForeignKey("transaction_id")]
        [InverseProperty("EscrowJams")]
        public virtual Transaction transaction { get; set; }
    }
}