// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("FailedTransactionResult", Schema = "rpt")]
    public partial class FailedTransactionResult
    {
        [Key]
        public Guid tx_id { get; set; }
        public DateTime gen_date { get; set; }
    }
}