// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    public partial class GetFailedPostTransactionsByDateResult
    {
        public Guid id { get; set; }
        public string tx_type { get; set; }
        public Guid session_id { get; set; }
        public int? tx_random_number { get; set; }
        public string device_name { get; set; }
        public DateTime tx_start_date { get; set; }
        public DateTime? tx_end_date { get; set; }
        public string tx_currency { get; set; }
        public decimal? tx_amount { get; set; }
        public string tx_account_number { get; set; }
        public string cb_account_name { get; set; }
        public string tx_ref_account { get; set; }
        public string cb_ref_account_name { get; set; }
        public string tx_narration { get; set; }
        public string tx_depositor_name { get; set; }
        public string tx_id_number { get; set; }
        public string tx_phone { get; set; }
        public string funds_source { get; set; }
        public int tx_result { get; set; }
        public int tx_error_code { get; set; }
        public string tx_error_message { get; set; }
        public string cb_tx_number { get; set; }
        public DateTime? cb_date { get; set; }
        public string cb_tx_status { get; set; }
        public string cb_status_detail { get; set; }
        public bool notes_rejected { get; set; }
        public bool jam_detected { get; set; }
        public bool escrow_jam { get; set; }
        public Guid? cit_id { get; set; }
    }
}
