// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("GUIPrepopItem")]
    [Index("value", Name = "iValue_GUIPrepopItem")]
    public partial class GUIPrepopItem
    {
        public GUIPrepopItem()
        {
            GUIPrepopList_Items = new HashSet<GUIPrepopList_Item>();
        }

        [Key]
        public Guid id { get; set; }
        [Required]
        [StringLength(50)]
        public string name { get; set; }
        [StringLength(100)]
        public string description { get; set; }
        public Guid value { get; set; }
        [Required]
        public bool? enabled { get; set; }

        [ForeignKey("value")]
        [InverseProperty("GUIPrepopItems")]
        public virtual TextItem valueNavigation { get; set; }
        [InverseProperty("ItemNavigation")]
        public virtual ICollection<GUIPrepopList_Item> GUIPrepopList_Items { get; set; }
    }
}