// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("GUIPrepopList_Item")]
    [Index("Item", "List", Name = "UX_GUIPrepopList_Item", IsUnique = true)]
    [Index("List_Order", "List", Name = "UX_GUIPrepopList_ListOrder", IsUnique = true)]
    [Index("Item", Name = "iItem_GUIPrepopList_Item")]
    [Index("List", Name = "iList_GUIPrepopList_Item")]
    public partial class GUIPrepopList_Item
    {
        [Key]
        public Guid id { get; set; }
        public Guid List { get; set; }
        public Guid Item { get; set; }
        public int List_Order { get; set; }

        [ForeignKey("Item")]
        [InverseProperty("GUIPrepopList_Items")]
        public virtual GUIPrepopItem ItemNavigation { get; set; }
        [ForeignKey("List")]
        [InverseProperty("GUIPrepopList_Items")]
        public virtual GUIPrepopList ListNavigation { get; set; }
    }
}