// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("GUIPrepopList")]
    public partial class GUIPrepopList
    {
        public GUIPrepopList()
        {
            GUIPrepopList_Items = new HashSet<GUIPrepopList_Item>();
            GuiScreenList_Screens = new HashSet<GuiScreenList_Screen>();
        }

        [Key]
        public Guid id { get; set; }
        [Required]
        [StringLength(50)]
        public string name { get; set; }
        [StringLength(100)]
        public string description { get; set; }
        [Required]
        public bool? enabled { get; set; }
        public bool AllowFreeText { get; set; }
        public int DefaultIndex { get; set; }
        [Required]
        public bool? UseDefault { get; set; }

        [InverseProperty("ListNavigation")]
        public virtual ICollection<GUIPrepopList_Item> GUIPrepopList_Items { get; set; }
        [InverseProperty("guiprepoplist")]
        public virtual ICollection<GuiScreenList_Screen> GuiScreenList_Screens { get; set; }
    }
}