// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("GUIScreenType")]
    public partial class GUIScreenType
    {
        public GUIScreenType()
        {
            GUIScreens = new HashSet<GUIScreen>();
        }

        [Key]
        public int id { get; set; }
        public Guid code { get; set; }
        [Required]
        [StringLength(50)]
        public string name { get; set; }
        [StringLength(255)]
        public string description { get; set; }
        public bool enabled { get; set; }

        [InverseProperty("typeNavigation")]
        public virtual ICollection<GUIScreen> GUIScreens { get; set; }
    }
}