// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("GUIScreenList")]
    public partial class GUIScreenList
    {
        public GUIScreenList()
        {
            Devices = new HashSet<Device>();
            GuiScreenList_Screens = new HashSet<GuiScreenList_Screen>();
            TransactionTypeListItems = new HashSet<TransactionTypeListItem>();
        }

        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(50)]
        public string name { get; set; }
        [StringLength(255)]
        public string description { get; set; }
        public bool enabled { get; set; }

        [InverseProperty("GUIScreen_listNavigation")]
        public virtual ICollection<Device> Devices { get; set; }
        [InverseProperty("gui_screen_listNavigation")]
        public virtual ICollection<GuiScreenList_Screen> GuiScreenList_Screens { get; set; }
        [InverseProperty("tx_type_guiscreenlistNavigation")]
        public virtual ICollection<TransactionTypeListItem> TransactionTypeListItems { get; set; }
    }
}