// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("GUIScreen")]
    [Index("gui_text", Name = "igui_text_GUIScreen")]
    [Index("type", Name = "itype_GUIScreen")]
    public partial class GUIScreen
    {
        public GUIScreen()
        {
            GuiScreenList_Screens = new HashSet<GuiScreenList_Screen>();
        }

        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(50)]
        public string name { get; set; }
        [StringLength(255)]
        public string description { get; set; }
        public int type { get; set; }
        public bool enabled { get; set; }
        public int? keyboard { get; set; }
        public bool? is_masked { get; set; }
        /// <summary>
        /// Text to prefil in the textbox
        /// </summary>
        [StringLength(50)]
        public string prefill_text { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string input_mask { get; set; }
        public Guid? gui_text { get; set; }

        [ForeignKey("gui_text")]
        [InverseProperty("GUIScreens")]
        public virtual GUIScreenText gui_textNavigation { get; set; }
        [ForeignKey("type")]
        [InverseProperty("GUIScreens")]
        public virtual GUIScreenType typeNavigation { get; set; }
        [InverseProperty("guiscreen")]
        public virtual GUIScreenText GUIScreenText { get; set; }
        [InverseProperty("screenNavigation")]
        public virtual ICollection<GuiScreenList_Screen> GuiScreenList_Screens { get; set; }
    }
}