// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("GuiScreenList_Screen")]
    [Index("gui_screen_list", "screen_order", Name = "UX_GuiScreenList_Screen_Order", IsUnique = true)]
    [Index("gui_screen_list", "screen", Name = "UX_GuiScreenList_Screen_ScreenItem", IsUnique = true)]
    [Index("gui_screen_list", Name = "igui_screen_list_GuiScreenList_Screen")]
    [Index("guiprepoplist_id", Name = "iguiprepoplist_id_GuiScreenList_Screen")]
    [Index("screen", Name = "iscreen_GuiScreenList_Screen")]
    [Index("validation_list_id", Name = "ivalidation_list_id_GuiScreenList_Screen")]
    public partial class GuiScreenList_Screen
    {
        [Key]
        public Guid id { get; set; }
        public int screen { get; set; }
        public int gui_screen_list { get; set; }
        public int screen_order { get; set; }
        public bool required { get; set; }
        public Guid? validation_list_id { get; set; }
        public Guid? guiprepoplist_id { get; set; }
        public bool enabled { get; set; }

        [ForeignKey("gui_screen_list")]
        [InverseProperty("GuiScreenList_Screens")]
        public virtual GUIScreenList gui_screen_listNavigation { get; set; }
        [ForeignKey("guiprepoplist_id")]
        [InverseProperty("GuiScreenList_Screens")]
        public virtual GUIPrepopList guiprepoplist { get; set; }
        [ForeignKey("screen")]
        [InverseProperty("GuiScreenList_Screens")]
        public virtual GUIScreen screenNavigation { get; set; }
        [ForeignKey("validation_list_id")]
        [InverseProperty("GuiScreenList_Screens")]
        public virtual ValidationList validation_list { get; set; }
    }
}