// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("KeyStore", Schema = "sec")]
    public partial class KeyStore
    {
        [Key]
        [StringLength(50)]
        public string config_key { get; set; }
        [Required]
        public string config_value { get; set; }
    }
}