// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    /// <summary>
    /// Available languages in the system
    /// </summary>
    [Table("Language")]
    public partial class Language
    {
        public Language()
        {
            DepositorSessions = new HashSet<DepositorSession>();
            LanguageList_Languages = new HashSet<LanguageList_Language>();
            LanguageLists = new HashSet<LanguageList>();
            TextTranslations = new HashSet<TextTranslation>();
            sysTextTranslations = new HashSet<sysTextTranslation>();
        }

        [Key]
        [StringLength(5)]
        [Unicode(false)]
        public string code { get; set; }
        [Required]
        [StringLength(50)]
        public string name { get; set; }
        /// <summary>
        /// two character country code for the national flag to display for the language
        /// </summary>
        [Required]
        [StringLength(255)]
        public string flag { get; set; }
        /// <summary>
        /// whether the system supports the language
        /// </summary>
        public bool enabled { get; set; }

        [InverseProperty("language_codeNavigation")]
        public virtual ICollection<DepositorSession> DepositorSessions { get; set; }
        [InverseProperty("language_itemNavigation")]
        public virtual ICollection<LanguageList_Language> LanguageList_Languages { get; set; }
        [InverseProperty("default_languageNavigation")]
        public virtual ICollection<LanguageList> LanguageLists { get; set; }
        [InverseProperty("LanguageCodeNavigation")]
        public virtual ICollection<TextTranslation> TextTranslations { get; set; }
        [InverseProperty("LanguageCodeNavigation")]
        public virtual ICollection<sysTextTranslation> sysTextTranslations { get; set; }
    }
}