// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    /// <summary>
    /// A list of languages a device supports
    /// </summary>
    [Table("LanguageList")]
    [Index("default_language", Name = "idefault_language_LanguageList")]
    public partial class LanguageList
    {
        public LanguageList()
        {
            Devices = new HashSet<Device>();
            LanguageList_Languages = new HashSet<LanguageList_Language>();
        }

        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(50)]
        public string name { get; set; }
        [StringLength(100)]
        public string description { get; set; }
        [Required]
        public bool? enabled { get; set; }
        [Required]
        [StringLength(5)]
        [Unicode(false)]
        public string default_language { get; set; }

        [ForeignKey("default_language")]
        [InverseProperty("LanguageLists")]
        public virtual Language default_languageNavigation { get; set; }
        [InverseProperty("language_listNavigation")]
        public virtual ICollection<Device> Devices { get; set; }
        [InverseProperty("language_listNavigation")]
        public virtual ICollection<LanguageList_Language> LanguageList_Languages { get; set; }
    }
}