// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("MakerTypePermissionObject")]
    public partial class MakerTypePermissionObject
    {
        [Key]
        public Guid Oid { get; set; }
        public int? MakerState { get; set; }
        public int? CheckerState { get; set; }

        [ForeignKey("Oid")]
        [InverseProperty("MakerTypePermissionObject")]
        public virtual PermissionPolicyTypePermissionsObject OidNavigation { get; set; }
    }
}