// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Keyless]
    [Table("MakerCheckerAction")]
    public partial class MakerCheckerAction
    {
        public Guid id { get; set; }
        public Guid? initialising_user { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? init_date { get; set; }
        public Guid? authorising_user { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? auth_date { get; set; }
        public bool? auth_response { get; set; }
        [StringLength(100)]
        public string reason { get; set; }
    }
}