// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("ModelDifference")]
    [Index("GCRecord", Name = "iGCRecord_ModelDifference")]
    public partial class ModelDifference
    {
        public ModelDifference()
        {
            ModelDifferenceAspects = new HashSet<ModelDifferenceAspect>();
        }

        [Key]
        public Guid Oid { get; set; }
        [StringLength(100)]
        public string UserId { get; set; }
        [StringLength(100)]
        public string ContextId { get; set; }
        public int? Version { get; set; }
        public int? OptimisticLockField { get; set; }
        public int? GCRecord { get; set; }

        [InverseProperty("OwnerNavigation")]
        public virtual ICollection<ModelDifferenceAspect> ModelDifferenceAspects { get; set; }
    }
}