// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    public partial class PermissionPolicyUserUsers_PermissionPolicyRoleRole
    {
        public Guid? Roles { get; set; }
        public Guid? Users { get; set; }
        [Key]
        public Guid OID { get; set; }
        public int? OptimisticLockField { get; set; }

        [ForeignKey("Roles")]
        [InverseProperty("PermissionPolicyUserUsers_PermissionPolicyRoleRoles")]
        public virtual PermissionPolicyRole RolesNavigation { get; set; }
        [ForeignKey("Users")]
        [InverseProperty("PermissionPolicyUserUsers_PermissionPolicyRoleRoles")]
        public virtual PermissionPolicyUser UsersNavigation { get; set; }
    }
}