// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("PermissionPolicyTypePermissionsObject")]
    [Index("GCRecord", Name = "iGCRecord_PermissionPolicyTypePermissionsObject")]
    [Index("ObjectType", Name = "iObjectType_PermissionPolicyTypePermissionsObject")]
    [Index("Role", Name = "iRole_PermissionPolicyTypePermissionsObject")]
    public partial class PermissionPolicyTypePermissionsObject
    {
        public PermissionPolicyTypePermissionsObject()
        {
            PermissionPolicyMemberPermissionsObjects = new HashSet<PermissionPolicyMemberPermissionsObject>();
            PermissionPolicyObjectPermissionsObjects = new HashSet<PermissionPolicyObjectPermissionsObject>();
        }

        [Key]
        public Guid Oid { get; set; }
        public Guid? Role { get; set; }
        public string TargetType { get; set; }
        public int? ReadState { get; set; }
        public int? WriteState { get; set; }
        public int? CreateState { get; set; }
        public int? DeleteState { get; set; }
        public int? NavigateState { get; set; }
        public int? OptimisticLockField { get; set; }
        public int? GCRecord { get; set; }
        public int? ObjectType { get; set; }

        [ForeignKey("ObjectType")]
        [InverseProperty("PermissionPolicyTypePermissionsObjects")]
        public virtual XPObjectType ObjectTypeNavigation { get; set; }
        [ForeignKey("Role")]
        [InverseProperty("PermissionPolicyTypePermissionsObjects")]
        public virtual PermissionPolicyRole RoleNavigation { get; set; }
        [InverseProperty("OidNavigation")]
        public virtual MakerTypePermissionObject MakerTypePermissionObject { get; set; }
        [InverseProperty("TypePermissionObjectNavigation")]
        public virtual ICollection<PermissionPolicyMemberPermissionsObject> PermissionPolicyMemberPermissionsObjects { get; set; }
        [InverseProperty("TypePermissionObjectNavigation")]
        public virtual ICollection<PermissionPolicyObjectPermissionsObject> PermissionPolicyObjectPermissionsObjects { get; set; }
    }
}