// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    /// <summary>
    /// grant a role to perform an activity
    /// </summary>
    [Table("Permission")]
    [Index("role_id", "activity_id", Name = "UX_Permission", IsUnique = true)]
    [Index("activity_id", Name = "iactivity_id_Permission")]
    [Index("role_id", Name = "irole_id_Permission")]
    public partial class Permission
    {
        [Key]
        public Guid id { get; set; }
        public Guid role_id { get; set; }
        public Guid activity_id { get; set; }
        public bool standalone_allowed { get; set; }
        public bool standalone_authentication_required { get; set; }
        public bool standalone_can_Authenticate { get; set; }

        [ForeignKey("activity_id")]
        [InverseProperty("Permissions")]
        public virtual Activity activity { get; set; }
        [ForeignKey("role_id")]
        [InverseProperty("Permissions")]
        public virtual Role role { get; set; }
    }
}