// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("PingResponse", Schema = "cb")]
    public partial class PingResponse
    {
        [Key]
        [StringLength(20)]
        public string ServerName { get; set; }
        public DateTime UpdateTime { get; set; }
        public bool IsSuccess { get; set; }
        public bool ServerOnline { get; set; }
        [StringLength(10)]
        public string ErrorCode { get; set; }
        [StringLength(200)]
        public string ErrorMessage { get; set; }
    }
}