// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    /// <summary>
    /// Stores contents of a printout for a transaction
    /// </summary>
    [Table("Printout")]
    [Index("tx_id", Name = "itx_id_Printout")]
    public partial class Printout
    {
        [Key]
        public Guid id { get; set; }
        public DateTime datetime { get; set; }
        public Guid tx_id { get; set; }
        public Guid print_guid { get; set; }
        public string print_content { get; set; }
        public bool is_copy { get; set; }

        [ForeignKey("tx_id")]
        [InverseProperty("Printouts")]
        public virtual Transaction tx { get; set; }
    }
}