// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    public partial class procInsCITPostingResult
    {
        public Guid? Identifier { get; set; }
        public string error { get; set; }
    }
}
