// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("TextTranslation", Schema = "xlns")]
    [Index("LanguageCode", "TextItemID", Name = "UX_UI_Translation_Language_Pair", IsUnique = true)]
    [Index("LanguageCode", Name = "iLanguageCode_xlns_TextTranslation_0EDE47B6")]
    [Index("TextItemID", Name = "iTextItemID_xlns_TextTranslation_00B6C5AC")]
    public partial class TextTranslation
    {
        [Key]
        public Guid id { get; set; }
        public Guid TextItemID { get; set; }
        [Required]
        [StringLength(5)]
        [Unicode(false)]
        public string LanguageCode { get; set; }
        [Required]
        public string TranslationText { get; set; }

        [ForeignKey("LanguageCode")]
        [InverseProperty("TextTranslations")]
        public virtual Language LanguageCodeNavigation { get; set; }
        [ForeignKey("TextItemID")]
        [InverseProperty("TextTranslations")]
        public virtual TextItem TextItem { get; set; }
    }
}