// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    /// <summary>
    /// Stores the multi language texts for a tx
    /// </summary>
    [Table("TransactionText")]
    [Index("tx_item", Name = "UX_TransactionText_tx_item", IsUnique = true)]
    [Index("FundsSource_caption", Name = "iFundsSource_caption_TransactionText")]
    [Index("account_name_caption", Name = "iaccount_name_caption_TransactionText")]
    [Index("account_number_caption", Name = "iaccount_number_caption_TransactionText")]
    [Index("alias_account_name_caption", Name = "ialias_account_name_caption_TransactionText")]
    [Index("alias_account_number_caption", Name = "ialias_account_number_caption_TransactionText")]
    [Index("depositor_name_caption", Name = "idepositor_name_caption_TransactionText")]
    [Index("disclaimer", Name = "idisclaimer_TransactionText")]
    [Index("full_instructions", Name = "ifull_instructions_TransactionText")]
    [Index("id_number_caption", Name = "iid_number_caption_TransactionText")]
    [Index("listItem_caption", Name = "ilistItem_caption_TransactionText")]
    [Index("narration_caption", Name = "inarration_caption_TransactionText")]
    [Index("phone_number_caption", Name = "iphone_number_caption_TransactionText")]
    [Index("receipt_template", Name = "ireceipt_template_TransactionText")]
    [Index("reference_account_name_caption", Name = "ireference_account_name_caption_TransactionText")]
    [Index("reference_account_number_caption", Name = "ireference_account_number_caption_TransactionText")]
    [Index("terms", Name = "iterms_TransactionText")]
    [Index("tx_item", Name = "itx_item_TransactionText")]
    public partial class TransactionText
    {
        public TransactionText()
        {
            TransactionTypeListItems = new HashSet<TransactionTypeListItem>();
        }

        [Key]
        public Guid id { get; set; }
        public int tx_item { get; set; }
        public Guid? disclaimer { get; set; }
        public Guid? terms { get; set; }
        public Guid? full_instructions { get; set; }
        public Guid? listItem_caption { get; set; }
        public Guid? account_number_caption { get; set; }
        public Guid? account_name_caption { get; set; }
        public Guid? reference_account_number_caption { get; set; }
        public Guid? reference_account_name_caption { get; set; }
        public Guid? narration_caption { get; set; }
        public Guid? alias_account_number_caption { get; set; }
        public Guid? alias_account_name_caption { get; set; }
        public Guid? depositor_name_caption { get; set; }
        public Guid? phone_number_caption { get; set; }
        public Guid? id_number_caption { get; set; }
        public Guid? receipt_template { get; set; }
        public Guid? FundsSource_caption { get; set; }

        [ForeignKey("FundsSource_caption")]
        [InverseProperty("TransactionTextFundsSource_captionNavigations")]
        public virtual TextItem FundsSource_captionNavigation { get; set; }
        [ForeignKey("account_name_caption")]
        [InverseProperty("TransactionTextaccount_name_captionNavigations")]
        public virtual TextItem account_name_captionNavigation { get; set; }
        [ForeignKey("account_number_caption")]
        [InverseProperty("TransactionTextaccount_number_captionNavigations")]
        public virtual TextItem account_number_captionNavigation { get; set; }
        [ForeignKey("alias_account_name_caption")]
        [InverseProperty("TransactionTextalias_account_name_captionNavigations")]
        public virtual TextItem alias_account_name_captionNavigation { get; set; }
        [ForeignKey("alias_account_number_caption")]
        [InverseProperty("TransactionTextalias_account_number_captionNavigations")]
        public virtual TextItem alias_account_number_captionNavigation { get; set; }
        [ForeignKey("depositor_name_caption")]
        [InverseProperty("TransactionTextdepositor_name_captionNavigations")]
        public virtual TextItem depositor_name_captionNavigation { get; set; }
        [ForeignKey("disclaimer")]
        [InverseProperty("TransactionTextdisclaimerNavigations")]
        public virtual TextItem disclaimerNavigation { get; set; }
        [ForeignKey("full_instructions")]
        [InverseProperty("TransactionTextfull_instructionsNavigations")]
        public virtual TextItem full_instructionsNavigation { get; set; }
        [ForeignKey("id_number_caption")]
        [InverseProperty("TransactionTextid_number_captionNavigations")]
        public virtual TextItem id_number_captionNavigation { get; set; }
        [ForeignKey("listItem_caption")]
        [InverseProperty("TransactionTextlistItem_captionNavigations")]
        public virtual TextItem listItem_captionNavigation { get; set; }
        [ForeignKey("narration_caption")]
        [InverseProperty("TransactionTextnarration_captionNavigations")]
        public virtual TextItem narration_captionNavigation { get; set; }
        [ForeignKey("phone_number_caption")]
        [InverseProperty("TransactionTextphone_number_captionNavigations")]
        public virtual TextItem phone_number_captionNavigation { get; set; }
        [ForeignKey("receipt_template")]
        [InverseProperty("TransactionTextreceipt_templateNavigations")]
        public virtual TextItem receipt_templateNavigation { get; set; }
        [ForeignKey("reference_account_name_caption")]
        [InverseProperty("TransactionTextreference_account_name_captionNavigations")]
        public virtual TextItem reference_account_name_captionNavigation { get; set; }
        [ForeignKey("reference_account_number_caption")]
        [InverseProperty("TransactionTextreference_account_number_captionNavigations")]
        public virtual TextItem reference_account_number_captionNavigation { get; set; }
        [ForeignKey("terms")]
        [InverseProperty("TransactionTexttermsNavigations")]
        public virtual TextItem termsNavigation { get; set; }
        [ForeignKey("tx_item")]
        [InverseProperty("TransactionText")]
        public virtual TransactionTypeListItem tx_itemNavigation { get; set; }
        [InverseProperty("tx_textNavigation")]
        public virtual ICollection<TransactionTypeListItem> TransactionTypeListItems { get; set; }
    }
}