// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("TransactionTypeList_TransactionTypeListItem")]
    [Index("txtype_list", "txtype_list_item", Name = "UX_TransactionTypeList_TransactionTypeListItem_Item", IsUnique = true)]
    [Index("txtype_list", "list_order", Name = "UX_TransactionTypeList_TransactionTypeListItem_Order", IsUnique = true)]
    [Index("txtype_list", Name = "itxtype_list_TransactionTypeList_TransactionTypeListItem")]
    [Index("txtype_list_item", Name = "itxtype_list_item_TransactionTypeList_TransactionTypeListItem")]
    public partial class TransactionTypeList_TransactionTypeListItem
    {
        [Key]
        public Guid id { get; set; }
        public int txtype_list_item { get; set; }
        public int txtype_list { get; set; }
        public int list_order { get; set; }

        [ForeignKey("txtype_list")]
        [InverseProperty("TransactionTypeList_TransactionTypeListItems")]
        public virtual TransactionTypeList txtype_listNavigation { get; set; }
        [ForeignKey("txtype_list_item")]
        [InverseProperty("TransactionTypeList_TransactionTypeListItems")]
        public virtual TransactionTypeListItem txtype_list_itemNavigation { get; set; }
    }
}