// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    /// <summary>
    /// Limit values for each currency
    /// </summary>
    [Table("TransactionLimitListItem")]
    [Index("transactionitemlist_id", "currency_code", Name = "UX_TransactionLimitListItem", IsUnique = true)]
    [Index("currency_code", Name = "icurrency_code_TransactionLimitListItem")]
    [Index("transactionitemlist_id", Name = "itransactionitemlist_id_TransactionLimitListItem")]
    public partial class TransactionLimitListItem
    {
        [Key]
        public Guid id { get; set; }
        public Guid transactionitemlist_id { get; set; }
        /// <summary>
        /// ISO 4217 Three Character Currency Code
        /// </summary>
        [Required]
        [StringLength(3)]
        [Unicode(false)]
        public string currency_code { get; set; }
        /// <summary>
        /// Whether to show the source of funds screen after deposit limit is reached or passed
        /// </summary>
        public bool show_funds_source { get; set; }
        public Guid? show_funds_form { get; set; }
        /// <summary>
        /// The amount after which the Source of Funds screen will be shown
        /// </summary>
        public long funds_source_amount { get; set; }
        /// <summary>
        /// CDM will not accept further deposits past the maximum
        /// </summary>
        public bool prevent_overdeposit { get; set; }
        /// <summary>
        /// The amount after which the CDM will disable the counter
        /// </summary>
        public long overdeposit_amount { get; set; }
        [Required]
        public bool? prevent_underdeposit { get; set; }
        public long underdeposit_amount { get; set; }
        public bool prevent_overcount { get; set; }
        public int overcount_amount { get; set; }

        [ForeignKey("currency_code")]
        [InverseProperty("TransactionLimitListItems")]
        public virtual Currency currency_codeNavigation { get; set; }
        [ForeignKey("transactionitemlist_id")]
        [InverseProperty("TransactionLimitListItems")]
        public virtual TransactionLimitList transactionitemlist { get; set; }
    }
}