// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    /// <summary>
    /// Exceptions encountered during execution
    /// </summary>
    [Table("TransactionException", Schema = "exp")]
    [Index("transaction_id", Name = "itransaction_id_exp_TransactionException_0990CC78")]
    public partial class TransactionException
    {
        [Key]
        public Guid id { get; set; }
        public DateTime datetime { get; set; }
        public Guid transaction_id { get; set; }
        public int code { get; set; }
        public int level { get; set; }
        [StringLength(255)]
        public string additional_info { get; set; }
        [StringLength(255)]
        public string message { get; set; }
        [Required]
        [StringLength(50)]
        public string machine_name { get; set; }
    }
}