// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("TransactionTypeList")]
    public partial class TransactionTypeList
    {
        public TransactionTypeList()
        {
            Devices = new HashSet<Device>();
            TransactionTypeList_TransactionTypeListItems = new HashSet<TransactionTypeList_TransactionTypeListItem>();
        }

        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(50)]
        public string name { get; set; }
        [StringLength(255)]
        public string description { get; set; }
        public bool enabled { get; set; }

        [InverseProperty("transaction_type_listNavigation")]
        public virtual ICollection<Device> Devices { get; set; }
        [InverseProperty("txtype_listNavigation")]
        public virtual ICollection<TransactionTypeList_TransactionTypeListItem> TransactionTypeList_TransactionTypeListItems { get; set; }
    }
}