// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    /// <summary>
    /// Individual values for the validation
    /// </summary>
    [Table("ValidationItemValue")]
    [Index("validation_item_id", "order", Name = "UX_ValidationItemValue", IsUnique = true)]
    [Index("validation_item_id", Name = "ivalidation_item_id_ValidationItemValue")]
    public partial class ValidationItemValue
    {
        [Key]
        public Guid id { get; set; }
        public Guid validation_item_id { get; set; }
        [Required]
        [StringLength(255)]
        public string value { get; set; }
        public int order { get; set; }

        [ForeignKey("validation_item_id")]
        [InverseProperty("ValidationItemValues")]
        public virtual ValidationItem validation_item { get; set; }
    }
}