// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    /// <summary>
    /// List of validations to be performed on a field
    /// </summary>
    [Table("ValidationList")]
    public partial class ValidationList
    {
        public ValidationList()
        {
            GuiScreenList_Screens = new HashSet<GuiScreenList_Screen>();
            ValidationList_ValidationItems = new HashSet<ValidationList_ValidationItem>();
        }

        [Key]
        public Guid id { get; set; }
        /// <summary>
        /// common name for the transaction e.g. Mpesa Deposit
        /// </summary>
        [Required]
        [StringLength(50)]
        public string name { get; set; }
        /// <summary>
        /// common description for the transaction type
        /// </summary>
        [StringLength(255)]
        public string description { get; set; }
        [StringLength(25)]
        public string category { get; set; }
        public bool enabled { get; set; }

        [InverseProperty("validation_list")]
        public virtual ICollection<GuiScreenList_Screen> GuiScreenList_Screens { get; set; }
        [InverseProperty("validation_list")]
        public virtual ICollection<ValidationList_ValidationItem> ValidationList_ValidationItems { get; set; }
    }
}