// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    /// <summary>
    /// Multilanguage validation result text
    /// </summary>
    [Table("ValidationText")]
    [Index("error_message", Name = "ierror_message_ValidationText")]
    [Index("success_message", Name = "isuccess_message_ValidationText")]
    [Index("validation_item_id", Name = "ivalidation_item_id_ValidationText")]
    public partial class ValidationText
    {
        public ValidationText()
        {
            ValidationItems = new HashSet<ValidationItem>();
        }

        [Key]
        public Guid id { get; set; }
        public Guid validation_item_id { get; set; }
        public Guid? error_message { get; set; }
        public Guid? success_message { get; set; }

        [ForeignKey("error_message")]
        [InverseProperty("ValidationTexterror_messageNavigations")]
        public virtual TextItem error_messageNavigation { get; set; }
        [ForeignKey("success_message")]
        [InverseProperty("ValidationTextsuccess_messageNavigations")]
        public virtual TextItem success_messageNavigation { get; set; }
        [ForeignKey("validation_item_id")]
        [InverseProperty("ValidationTexts")]
        public virtual ValidationItem validation_item { get; set; }
        [InverseProperty("validation_text")]
        public virtual ICollection<ValidationItem> ValidationItems { get; set; }
    }
}