// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("ValidationItem")]
    [Index("type_id", Name = "itype_id_ValidationItem")]
    [Index("validation_text_id", Name = "ivalidation_text_id_ValidationItem")]
    public partial class ValidationItem
    {
        public ValidationItem()
        {
            ValidationItemValues = new HashSet<ValidationItemValue>();
            ValidationList_ValidationItems = new HashSet<ValidationList_ValidationItem>();
            ValidationTexts = new HashSet<ValidationText>();
        }

        [Key]
        public Guid id { get; set; }
        /// <summary>
        /// common name for the transaction e.g. Mpesa Deposit
        /// </summary>
        [Required]
        [StringLength(50)]
        public string name { get; set; }
        [StringLength(10)]
        public string category { get; set; }
        /// <summary>
        /// common description for the transaction type
        /// </summary>
        [StringLength(255)]
        public string description { get; set; }
        public Guid type_id { get; set; }
        public bool enabled { get; set; }
        public int? error_code { get; set; }
        public Guid? validation_text_id { get; set; }

        [ForeignKey("type_id")]
        [InverseProperty("ValidationItems")]
        public virtual ValidationType type { get; set; }
        [ForeignKey("validation_text_id")]
        [InverseProperty("ValidationItems")]
        public virtual ValidationText validation_text { get; set; }
        [InverseProperty("validation_item")]
        public virtual ICollection<ValidationItemValue> ValidationItemValues { get; set; }
        [InverseProperty("validation_item")]
        public virtual ICollection<ValidationList_ValidationItem> ValidationList_ValidationItems { get; set; }
        [InverseProperty("validation_item")]
        public virtual ICollection<ValidationText> ValidationTexts { get; set; }
    }
}