// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Index("ApplicationUsers", "Roles", Name = "iApplicationUsersRoles_WebPortalRoleRoles_ApplicationUserApplicationUsers", IsUnique = true)]
    [Index("ApplicationUsers", Name = "iApplicationUsers_WebPortalRoleRoles_ApplicationUserApplicationUsers")]
    [Index("Roles", Name = "iRoles_PermissionPolicyUserUsers_PermissionPolicyRoleRoles")]
    [Index("Roles", Name = "iRoles_WebPortalRoleRoles_ApplicationUserApplicationUsers")]
    public partial class WebPortalRoleRoles_ApplicationUserApplicationUser
    {
        public Guid? Roles { get; set; }
        [Key]
        public Guid OID { get; set; }
        public int? OptimisticLockField { get; set; }
        public Guid? ApplicationUsers { get; set; }

        [ForeignKey("ApplicationUsers")]
        [InverseProperty("WebPortalRoleRoles_ApplicationUserApplicationUsers")]
        public virtual ApplicationUser ApplicationUsersNavigation { get; set; }
        [ForeignKey("Roles")]
        [InverseProperty("WebPortalRoleRoles_ApplicationUserApplicationUsers")]
        public virtual WebPortalRole RolesNavigation { get; set; }
    }
}