// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("WebPortalRole")]
    public partial class WebPortalRole
    {
        public WebPortalRole()
        {
            WebPortalRoleRoles_ApplicationUserApplicationUsers = new HashSet<WebPortalRoleRoles_ApplicationUserApplicationUser>();
        }

        [Key]
        public Guid Oid { get; set; }
        [StringLength(255)]
        public string description { get; set; }

        [ForeignKey("Oid")]
        [InverseProperty("WebPortalRole")]
        public virtual PermissionPolicyRole OidNavigation { get; set; }
        [InverseProperty("RolesNavigation")]
        public virtual ICollection<WebPortalRoleRoles_ApplicationUserApplicationUser> WebPortalRoleRoles_ApplicationUserApplicationUsers { get; set; }
    }
}