// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("WebPortalLogin")]
    [Index("ApplicationUserLoginDetail", Name = "iApplicationUserLoginDetail_WebPortalLogin")]
    [Index("SessionID", "WebPortalLoginAction", Name = "iSessionID_WebPortalLogin", IsUnique = true)]
    public partial class WebPortalLogin
    {
        public WebPortalLogin()
        {
            ApplicationUserLoginDetails = new HashSet<ApplicationUserLoginDetail>();
        }

        [Key]
        public Guid id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LogDate { get; set; }
        public Guid? ApplicationUserLoginDetail { get; set; }
        public int? WebPortalLoginAction { get; set; }
        public bool? Success { get; set; }
        public bool? IsActive { get; set; }
        public bool? ChangePassword { get; set; }
        [StringLength(200)]
        public string Message { get; set; }
        [StringLength(50)]
        public string SessionID { get; set; }
        [StringLength(50)]
        public string SFBegone { get; set; }
        [StringLength(128)]
        public string Hash { get; set; }

        [ForeignKey("ApplicationUserLoginDetail")]
        [InverseProperty("WebPortalLogins")]
        public virtual ApplicationUserLoginDetail ApplicationUserLoginDetailNavigation { get; set; }
        [InverseProperty("LastLoginLogEntryNavigation")]
        public virtual ICollection<ApplicationUserLoginDetail> ApplicationUserLoginDetails { get; set; }
    }
}