// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("WebUserLoginCount")]
    [Index("GCRecord", Name = "iGCRecord_WebUserLoginCount")]
    public partial class WebUserLoginCount
    {
        [Key]
        public Guid Oid { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? modified { get; set; }
        public int? loginCount { get; set; }
        [StringLength(100)]
        public string User { get; set; }
        public int? OptimisticLockField { get; set; }
        public int? GCRecord { get; set; }
    }
}