// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CashSwift.Finacle.Integration.DataAccess.Entities
{
    [Table("XPWeakReference")]
    [Index("GCRecord", Name = "iGCRecord_XPWeakReference")]
    [Index("ObjectType", Name = "iObjectType_XPWeakReference")]
    [Index("TargetType", Name = "iTargetType_XPWeakReference")]
    public partial class XPWeakReference
    {
        public XPWeakReference()
        {
            AuditDataItemPersistentNewObjectNavigations = new HashSet<AuditDataItemPersistent>();
            AuditDataItemPersistentOldObjectNavigations = new HashSet<AuditDataItemPersistent>();
        }

        [Key]
        public Guid Oid { get; set; }
        public int? TargetType { get; set; }
        [StringLength(100)]
        public string TargetKey { get; set; }
        public int? OptimisticLockField { get; set; }
        public int? GCRecord { get; set; }
        public int? ObjectType { get; set; }

        [ForeignKey("ObjectType")]
        [InverseProperty("XPWeakReferenceObjectTypeNavigations")]
        public virtual XPObjectType ObjectTypeNavigation { get; set; }
        [ForeignKey("TargetType")]
        [InverseProperty("XPWeakReferenceTargetTypeNavigations")]
        public virtual XPObjectType TargetTypeNavigation { get; set; }
        [InverseProperty("OidNavigation")]
        public virtual AuditedObjectWeakReference AuditedObjectWeakReference { get; set; }
        [InverseProperty("NewObjectNavigation")]
        public virtual ICollection<AuditDataItemPersistent> AuditDataItemPersistentNewObjectNavigations { get; set; }
        [InverseProperty("OldObjectNavigation")]
        public virtual ICollection<AuditDataItemPersistent> AuditDataItemPersistentOldObjectNavigations { get; set; }
    }
}